version: '3.8'
services:
  app:
    build:
      context: ./api
    container_name: api-container
    ports:
      - "4040:5005"
    networks:
      - api_default

  nginx:
    build:
      context: ./nginx
    container_name: nginx-container
    ports:
      - "8080:7070"
      - "8080:6060"
    networks:
      - api_default

networks:
  api_default:
    external: true

